
- name: Nginx Install and Run
  hosts: web
  become: yes  # Ensure the playbook runs with elevated sudo privileges
  tasks:
    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present
    - name: run nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
