---
- name: Create user
  hosts: web
  become: yes  # Run tasks with elevated privileges (root)
  tasks:
    - name: Check if user exists or not
      ansible.builtin.command: id expense  # Run the 'id' command to check if the user exists
      register: USER  # Register the result of the command in the variable 'USER'
      ignore_errors: True  # Ignore errors in case the user doesn't exist (the 'id' command will fail if user doesn't exist)

    - name: Print the user information
      ansible.builtin.debug:
        msg: "User info: {{ USER }}"  # Print the contents of the 'USER' variable (this contains the command output)

    - name: Create user
      ansible.builtin.command: useradd expense  # Run the 'useradd' command to create the user 'expense'
      when: USER.rc != 0  # Only run this task if the user doesn't exist (USER.rc != 0 means the previous command failed)
